### PR TITLE
add support for unsigned integers

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
As mentioned briefly in #130, I added support for unsigned integers. When adding unsigned + unsigned -> unsigned, but unsigned + signed -> signed.

Now the still missing datatypes are:
np.intp, np.uintp, np.complex64, np.complex128

But I am not entirely sure how to add them, and they are quite niche (even more so than unsigned ;) )

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
Ah, let me add some tests!

**Comment by thomkeh** [comment]
type-hinting tests are a big problem. I'm not really happy with how we're doing them, but I haven't found a better solution.

That said, something like this would be nice (in the numpy test file):

```python
def test_unsigned() -> None:
    x: np.ndarray[np.uint8] = np.array([3, 4], dtype=np.uint8)
    y: np.ndarray[np.uint8] = x + x
```

**Comment by Maarten-vd-Sande** [comment]
@thomkeh I added the tests. Thanks for the help :)

**Comment by thomkeh** [comment]
Great, thanks!

**Pull request merged**
