### PR TITLE
add MANIFEST.in

### LINKED ISSUE #204: gen_pyi.py not in tar ball from PyPI
MWE:

```sh
wget https://pypi.io/packages/source/d/data-science-types/data-science-types-0.2.21.tar.gz
tar -xvf data-science-types-0.2.21.tar.gz
tree
```

and you can see that `gen_pyi.py` is not there. However, `setup.py` calls it so it fails.

### PR DESCRIPTION
**Pull request by ickc**
close #204

### CODE REVIEW

**Comment by thomkeh** [comment]
Thanks! Do you not have to use `recursive-include` for the `tools/` directory? (I don't know much about MANIFEST.in...)

**Comment by ickc** [comment]
Good catch! Fixed.

**Comment by ickc** [comment]
Wait a second, I found some problems. Don't merge yet.

**Comment by ickc** [comment]
I tested that the sdist is now pip installable. It should have no problem now.

**Comment by thomkeh** [comment]
Great!

**Comment by thomkeh** [comment]
I created a new release: https://pypi.org/project/data-science-types/0.2.22/#files Let me know if there's still problems.

**Pull request merged**
