### PR TITLE
Adds the signature for an optional argument in np.savetxt

### PR DESCRIPTION
**Pull request by aguillon**

### CODE REVIEW

**Comment by olliethomas** [comment]
Run Black with line-length 100 then you should be all good.
`black -l 100 -t py36 -S .`

**Comment by thomkeh** [comment]
Thank you!

We use [black](https://github.com/psf/black) to format the stub files. You will need to format the file with black. Sorry that we don't mention it anywhere.

**Comment by thomkeh** [comment]
Perfect! Thank you!

**Comment by aguillon** [comment]
Thank you for your help and the quick merge (and the awesome project!). I look forward to contributing again.

**Pull request merged**
