### PR TITLE
Add stubs for to_pickle and read_pickle

### LINKED ISSUE #216: Fails type checking on dataframe.to_pickle
Running mypy with data-science-types on the following

```
import pandas as pd
df = pd.DataFrame({'a': [1]})
df.to_pickle('output.pkl')
```

Produces an error:
```
error: "Series[Any]" not callable
```

I would expect it to pass using [DataFrame.to_pickle](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html)

### PR DESCRIPTION
**Pull request by EdwardJRoss**
Resolves #216

### CODE REVIEW

**Comment by thomkeh** [comment]
So it seems the tests for python 3.9 are downloading a newer version of pandas (1.2) which has the problem mentioned in #215. Is it easy to fix that?

**Comment by thomkeh** [comment]
I'm actually a bit surprised that pandas already dropped python 3.6 support.

**Comment by EdwardJRoss** [comment]
I guess a workaround would be to use the previous version in the tests by updating [.github/workflows/test_correctness.yml](https://github.com/predictive-analytics-lab/data-science-types/blob/master/.github/workflows/test_correctness.yml#L25) to install `pandas<1.2`

I'm not really clear enough on `iloc` behaviour and the test intention on how to fix the test for Pandas 1.2.

**Comment by thomkeh** [comment]
Okay, then let's do this for now

> updating .github/workflows/test_correctness.yml to install pandas<1.2

You can just edit the file.

**Comment by thomkeh** [comment]
Great, thanks!

**Pull request merged**
