### PR TITLE
Adds read_json to the pandas type stubs.

### LINKED ISSUE #156: Add type information for read_json method.
There is currently type information for `read_csv`, `read_feather`, and `read_sql`, but no information for `read_json`.

### PR DESCRIPTION
**Pull request by lmcnichols**
This adds type information for `read_json` to `__init__.py`.

Fixes #156

### CODE REVIEW

**Comment by lmcnichols** [comment]
I'm a little confused because the black seems to be complaining about files I did not change.

**Comment by olliethomas** [comment]
Thanks for the PR! 

There was a new release of Black 2 days ago which has a slightly different opinion on how things should formatted in comparison to the previous version. There's another PR which reformats all files with the latest Black (#155 ), it's just not in master yet. I think the best thing to do is update your dependencies locally (`pip install -U --no-cache-dir -e .[dev]`), then the CI will stop complaining 😅

**Comment by thomkeh** [comment]
The PR fixing the black problem has been merged now. You can either rebase your branch on top of master or you merge master into your branch.

**Comment by lmcnichols** [comment]
Ah terrific! I'll do that now.

**Comment by thomkeh** [comment]
Thanks!

**Pull request merged**
