### PR TITLE
let int indices for column labels for the df.at property

### PR DESCRIPTION
**Pull request by ZeeD**
fix to issue #152

### CODE REVIEW

**Comment by thomkeh** [comment]
Ah, the old issue that column names can also be integers. I think there was a previous PR where we determined that the correct type for columns should actually be `Hashable`. So, I would suggest the following:

- rename `_StrLike` to `_ColType` in the whole file
- define `_ColType` like this: `Union[Hashable, _np.str_]` (you will have to import `Hashable` from `typing`)

That should solve your problem.

```
In [1]: from typing import Hashable

In [2]: isinstance(6, Hashable)
Out[2]: True

In [3]: isinstance(6.4, Hashable)
Out[3]: True

In [4]: isinstance([], Hashable)
Out[4]: False
```

**Comment by ZeeD** [comment]
isn't `_np.str_` also `Hashable`?

```python
>>> from typing import Hashable
>>> import numpy as _np
>>> isinstance(_np.str_(), Hashable)
True
```

can I just use `Hashable` and drop `_StrLike` / `_ColType`?

**Comment by thomkeh** [comment]
Ok, sure.

**Comment by ZeeD** [comment]
uhm... I'm having trouble understanding the black check... putting aside the fact that the fails are on files/rows I didn't touched, I can't reproduce the same error on my machine... what is the exact command launched?

Surely, I can apply the diff, but is it something that should go in this PR?

**Comment by thomkeh** [comment]
The reason was the `black` pushed a new release which changed how it works. And GitHub CI always just downloads the latest version. Maybe we should pin one version of black.

**Pull request merged**
